services:
  postgres:
    image: postgres:17-alpine
    container_name: postgres-turing
    restart: unless-stopped
    environment:
      POSTGRES_USER: turing
      POSTGRES_PASSWORD: turing123
      POSTGRES_DB: turing_machine
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./turing.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U turing -d turing_machine"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
